builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
    - freebsd
  goarch:
    - 386
    - amd64
    - arm
    - arm64
archives:
  - id: windows
    replacements:
      386: i386
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
signs:
  - artifacts: checksum
